In [1]:
Q = [0 1 2 1 2 3 3 3 1 0 ; 1 1 2 2 2 2 3 3 1 1 ; 1 2 2 1 3 1 3 1 1 1 ; 0 1 0 0 1 1 0 0 1 1; 0 0 0 0 1 2 3 1 2 1; 0 0 0 0 1 1 1 2 1 1; 0 0 0 0 2 2 2 7 1 1; 0 0 0 0 3 4 3 4 1 4; 0 0 0 0 3 1 4 1 5 6; 0 0 0 0 6 3 4 1 2 1]

10×10 Matrix{Int64}:
 0  1  2  1  2  3  3  3  1  0
 1  1  2  2  2  2  3  3  1  1
 1  2  2  1  3  1  3  1  1  1
 0  1  0  0  1  1  0  0  1  1
 0  0  0  0  1  2  3  1  2  1
 0  0  0  0  1  1  1  2  1  1
 0  0  0  0  2  2  2  7  1  1
 0  0  0  0  3  4  3  4  1  4
 0  0  0  0  3  1  4  1  5  6
 0  0  0  0  6  3  4  1  2  1

In [3]:
using LinearAlgebra
det(Q)

-1012.0

In [4]:
A = [0 1 2 1; 1 1 2 2; 1 2 2 1; 0 1 0 0]

4×4 Matrix{Int64}:
 0  1  2  1
 1  1  2  2
 1  2  2  1
 0  1  0  0

In [5]:
det(A)

2.0

In [6]:
-1 -3//7*-5

8//7

In [9]:
-3 + 49//8*8//7

4//1

In [34]:
D = [1 2 3 1 2 1; 1 1 1 2 1 1; 2 2 2 7 1 1; 3 4 3 4 1 4; 3 1 4 1 5 6; 6 3 4 1 2 1]

6×6 Matrix{Int64}:
 1  2  3  1  2  1
 1  1  1  2  1  1
 2  2  2  7  1  1
 3  4  3  4  1  4
 3  1  4  1  5  6
 6  3  4  1  2  1

In [35]:
det(D)

-506.0

In [12]:
factorize(D)

LU{Float64, Matrix{Float64}}
L factor:
6×6 Matrix{Float64}:
 1.0        0.0  0.0         0.0        0.0       0.0
 0.5        1.0  0.0         0.0        0.0       0.0
 0.5       -0.2  1.0         0.0        0.0       0.0
 0.333333   0.4  0.121212    1.0        0.0       0.0
 0.166667   0.6  0.787879   -0.431953   1.0       0.0
 0.166667   0.2  0.0606061   0.207101  -0.293893  1.0
U factor:
6×6 Matrix{Float64}:
 6.0  3.0  4.0  1.0       2.0        1.0
 0.0  2.5  1.0  3.5       0.0        3.5
 0.0  0.0  2.2  1.2       4.0        6.2
 0.0  0.0  0.0  5.12121  -0.151515  -1.48485
 0.0  0.0  0.0  0.0      -1.5503    -6.7929
 0.0  0.0  0.0  0.0       0.0       -1.9313

In [52]:
[0.0  0.0  0.0  0.0  -12.3333  -8.33333] .* 3

1×6 Matrix{Float64}:
 0.0  0.0  0.0  0.0  -36.9999  -25.0

In [56]:
- 37/20 * 7

-12.950000000000001

In [55]:
[-37 -25] - 37/20 * [-20 7]

1×2 Matrix{Float64}:
 0.0  -37.95

In [70]:
D2 = [1 2 3 1 2 1; 0 -1 -2 1 -1 0; 0 0 -2 -1 -3 1; 0 0 0 3 -1 -1; 0 0 0 0 -20/3 7/3; 0 0 0 0 0 253/20]

6×6 Matrix{Float64}:
 1.0   2.0   3.0   1.0   2.0       1.0
 0.0  -1.0  -2.0   1.0  -1.0       0.0
 0.0   0.0  -2.0  -1.0  -3.0       1.0
 0.0   0.0   0.0   3.0  -1.0      -1.0
 0.0   0.0   0.0   0.0  -6.66667   2.33333
 0.0   0.0   0.0   0.0   0.0      12.65

In [71]:
det(D2)

-506.0

In [62]:
k = [0 0 0 -9.5 -3.5 5.5] + 9.5/3 * [0 0 0 3 -1 -1]

1×6 Matrix{Float64}:
 0.0  0.0  0.0  0.0  -6.66667  2.33333

In [69]:
-25//3 - 37//20 * (7//3)

-253//20

In [21]:
function eliminacao_gauss(A::Matrix{Float64}, b::Vector{Float64})

    M = hcat(A, b)
    
    for i in 1:length(M[:, 1])
        #pivotamento(i, i, M)
        pivot_line = M[i, :]
        for j in (i+1):(length(M[1, :])-1)
            m = M[j, i]/pivot_line[i]
            M[j, :] -= m * pivot_line
        end
    end

    return M[:, 1:(end-1)], M[:, end]
    
end

eliminacao_gauss (generic function with 1 method)

In [25]:
X = eliminacao_gauss(convert.(Float64, D2), zeros(6))

([1.0 2.0 … 2.0 1.0; 0.0 -1.0 … -1.0 0.0; … ; NaN NaN … NaN NaN; NaN NaN … NaN NaN], [0.0, 0.0, 0.0, NaN, NaN, NaN])

In [26]:
X[1]

6×6 Matrix{Float64}:
   1.0    2.0    3.0    1.0    2.0    1.0
   0.0   -1.0   -2.0    1.0   -1.0    0.0
   0.0    0.0    0.0    3.0   -1.0    1.0
 NaN    NaN    NaN     Inf   -Inf    Inf
 NaN    NaN    NaN    NaN    NaN    NaN
 NaN    NaN    NaN    NaN    NaN    NaN

In [72]:
-1*-1*-2*3*-20/3*-253/20

-506.0