In [ ]:
#using Pkg
#Pkg.installed()

In [1]:
using CSV
using DataFrames

In [8]:
lap_times_raw = DataFrame(CSV.File("C:/Users/liber/Documents/GitHub/Portifolio/F1_dataset/lap_times.csv"))

526450×6 DataFrame
    Row │ raceId  driverId  lap    position  time      milliseconds 
        │ Int64   Int64     Int64  Int64     String    Int64        
────────┼───────────────────────────────────────────────────────────
      1 │    841        20      1         1  1:38.109         98109
      2 │    841        20      2         1  1:33.006         93006
      3 │    841        20      3         1  1:32.713         92713
      4 │    841        20      4         1  1:32.803         92803
      5 │    841        20      5         1  1:32.342         92342
      6 │    841        20      6         1  1:32.605         92605
      7 │    841        20      7         1  1:32.502         92502
      8 │    841        20      8         1  1:32.537         92537
   ⋮    │   ⋮        ⋮        ⋮       ⋮         ⋮           ⋮
 526444 │   1084       815     18        20  1:12.880         72880
 526445 │   1084       815     19        20  1:12.977         72977
 526446 │   1084       815     20        20  1:12.934         72934
 526447 │   1084       815     21        20  1:13.071         73071
 526448 │   1084       815     22        20  1:13.540         73540
 526449 │   1084       815     23        20  1:14.844         74844
 526450 │   1084       815     24        20  1:18.175         78175
                                                 526435 rows omitted

In [66]:
races = DataFrame(CSV.File("C:/Users/liber/Documents/GitHub/Portifolio/F1_dataset/races.csv"));
qualis = DataFrame(CSV.File("C:/Users/liber/Documents/GitHub/Portifolio/F1_dataset/qualifying.csv"))
dropmissing!(qualis)

9061×9 DataFrame
  Row │ qualifyId  raceId  driverId  constructorId  number  position  q1       ⋯
      │ Int64      Int64   Int64     Int64          Int64   Int64     String   ⋯
──────┼─────────────────────────────────────────────────────────────────────────
    1 │         1      18         1              1      22         1  1:26.572 ⋯
    2 │         2      18         9              2       4         2  1:26.103
    3 │         3      18         5              1      23         3  1:25.664
    4 │         4      18        13              6       2         4  1:25.994
    5 │         5      18         2              2       3         5  1:25.960 ⋯
    6 │         6      18        15              7      11         6  1:26.427
    7 │         7      18         3              3       7         7  1:26.295
    8 │         8      18        14              9       9         8  1:26.381
  ⋮   │     ⋮        ⋮        ⋮            ⋮          ⋮        ⋮         ⋮     ⋱
 9055 │      9406    1084       852            213      22        14  1:06.463 ⋯
 9056 │      9407    1084       846              1       4        15  1:06.330
 9057 │      9408    1084       817              1       3        16  1:06.613
 9058 │      9409    1084       840            117      18        17  1:06.847
 9059 │      9410    1084       855             51      24        18  1:06.901 ⋯
 9060 │      9411    1084       849              3       6        19  1:07.003
 9061 │      9412    1084        20            117       5        20  1:07.083
                                                 2 columns and 9046 rows omitted

In [31]:
races_period = races[2018 .<= races.year .<= 2021, :]
races_period = select(races_period, Not(:time));
dados = innerjoin(lap_times_raw, races_period, on = :raceId)

87959×22 DataFrame
   Row │ raceId  driverId  lap    position  time      milliseconds  year   rou ⋯
       │ Int64   Int64     Int64  Int64     String    Int64         Int64  Int ⋯
───────┼────────────────────────────────────────────────────────────────────────
     1 │    989       843     57        15  1:28.176         88176   2018      ⋯
     2 │    989       843     56        15  1:28.493         88493   2018
     3 │    989       843     55        15  1:28.326         88326   2018
     4 │    989       843     54        15  1:28.255         88255   2018
     5 │    989       843     53        15  1:28.298         88298   2018      ⋯
     6 │    989       843     52        15  1:28.681         88681   2018
     7 │    989       843     51        15  1:29.193         89193   2018
     8 │    989       843     50        15  1:32.205         92205   2018
   ⋮   │   ⋮        ⋮        ⋮       ⋮         ⋮           ⋮          ⋮      ⋮ ⋱
 87953 │   1073       847     20        17  1:32.053         92053   2021      ⋯
 87954 │   1073       847     21        17  1:31.065         91065   2021
 87955 │   1073       847     22        15  1:30.821         90821   2021
 87956 │   1073       847     23        15  1:30.647         90647   2021
 87957 │   1073       847     24        14  1:31.577         91577   2021      ⋯
 87958 │   1073       847     25        16  1:32.794         92794   2021
 87959 │   1073       847     26        18  2:46.262        166262   2021
                                               15 columns and 87944 rows omitted

In [67]:
qualis = qualis[(qualis.position .== 1), :]
qualis = qualis[:, [:raceId, :q3]]

436×2 DataFrame
 Row │ raceId  q3       
     │ Int64   String   
─────┼──────────────────
   1 │     18  1:26.714
   2 │     19  1:35.748
   3 │     20  1:33.096
   4 │     21  1:21.813
   5 │     22  1:27.617
   6 │     23  1:15.787
   7 │     24  1:17.886
   8 │     25  1:16.449
  ⋮  │   ⋮        ⋮
 430 │   1078  1:28.796
 431 │   1079  1:18.750
 432 │   1080  1:11.376
 433 │   1081  1:41.359
 434 │   1082  1:21.299
 435 │   1083  1:40.983
 436 │   1084  1:04.984
        421 rows omitted

In [72]:
v = "1:15.666"
v[(end-2):end]
function converter(string)
    try
        numero = split(string, ":")
        min = parse(Float64, numero[1])
        sec = parse(Float64, numero[2])
        total = sec*1000 + min*60*1000
        return total
    catch
        return 0
    end
end

converter (generic function with 1 method)

In [73]:
qualis.PACE = zeros(436)

436-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [69]:
converter(v)

75666.0

In [74]:
dropmissing!(qualis)
map!(converter, qualis.PACE, qualis[:, :q3])

436-element Vector{Float64}:
  86714.0
  95748.0
  93096.0
  81813.0
  87617.0
  75787.0
  77886.0
  76449.0
  81049.0
  75666.0
      ⋮
  77868.0
  87999.0
  88796.0
  78750.0
  71376.0
 101359.0
  81299.0
 100983.0
  64984.0

In [76]:
qualis = qualis[qualis.PACE .> 0, :]

317×3 DataFrame
 Row │ raceId  q3        PACE     
     │ Int64   String    Float64  
─────┼────────────────────────────
   1 │     18  1:26.714   86714.0
   2 │     19  1:35.748   95748.0
   3 │     20  1:33.096   93096.0
   4 │     21  1:21.813   81813.0
   5 │     22  1:27.617   87617.0
   6 │     23  1:15.787   75787.0
   7 │     24  1:17.886   77886.0
   8 │     25  1:16.449   76449.0
  ⋮  │   ⋮        ⋮         ⋮
 311 │   1078  1:28.796   88796.0
 312 │   1079  1:18.750   78750.0
 313 │   1080  1:11.376   71376.0
 314 │   1081  1:41.359  101359.0
 315 │   1082  1:21.299   81299.0
 316 │   1083  1:40.983  100983.0
 317 │   1084  1:04.984   64984.0
                  302 rows omitted

In [31]:
voltas_HAM = dados[dados.driverId .== 1, :]
CSV.write("C:/Users/liber/Desktop/Stats/3o Semestre/Pacotes/voltas_HAM", voltas_HAM)

"C:/Users/liber/Desktop/Stats/3o Semestre/Pacotes/voltas_HAM"

In [18]:
Drivers = DataFrame(CSV.File("C:/Users/liber/Documents/GitHub/Portifolio/F1_dataset/drivers.csv"))

854×9 DataFrame
 Row │ driverId  driverRef          number  code    forename   surname     dob ⋯
     │ Int64     String             String  String  String     String      Dat ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │        1  hamilton           44      HAM     Lewis      Hamilton    198 ⋯
   2 │        2  heidfeld           \\N     HEI     Nick       Heidfeld    197
   3 │        3  rosberg            6       ROS     Nico       Rosberg     198
   4 │        4  alonso             14      ALO     Fernando   Alonso      198
   5 │        5  kovalainen         \\N     KOV     Heikki     Kovalainen  198 ⋯
   6 │        6  nakajima           \\N     NAK     Kazuki     Nakajima    198
   7 │        7  bourdais           \\N     BOU     Sébastien  Bourdais    197
   8 │        8  raikkonen          7       RAI     Kimi       Räikkönen   197
  ⋮  │    ⋮              ⋮            ⋮       ⋮         ⋮          ⋮           ⋱
 848 │      849  latifi             6       LAT     Nicholas   Latifi      199 ⋯
 849 │      850  pietro_fittipaldi  51      FIT     Pietro     Fittipaldi  199
 850 │      851  aitken             89      AIT     Jack       Aitken      199
 851 │      852  tsunoda            22      TSU     Yuki       Tsunoda     200
 852 │      853  mazepin            9       MAZ     Nikita     Mazepin     199 ⋯
 853 │      854  mick_schumacher    47      MSC     Mick       Schumacher  199
 854 │      855  zhou               24      ZHO     Guanyu     Zhou        199
                                                  3 columns and 839 rows omitted

In [19]:
Drivers[Drivers.forename .== "Max", :]

4×9 DataFrame
 Row │ driverId  driverRef       number  code    forename  surname     dob     ⋯
     │ Int64     String          String  String  String    String      Date    ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │      349  jean            \\N     \\N     Max       Jean        1943-07 ⋯
   2 │      720  terra           \\N     \\N     Max       de Terra    1918-10
   3 │      820  chilton         4       CHI     Max       Chilton     1991-04
   4 │      830  max_verstappen  33      VER     Max       Verstappen  1997-09
                                                               3 columns omitted

In [30]:
voltas_VER = dados[dados.driverId .== 830, :]
CSV.write("C:/Users/liber/Desktop/Stats/3o Semestre/Pacotes/MAX.csv", voltas_VER)


"C:/Users/liber/Desktop/Stats/3o Semestre/Pacotes/MAX.csv"

In [26]:
#histogram(voltas_VER)
quantile(voltas_VER, [0.05, 0.9, 0.95, 0.975, 0.99])

5-element Vector{Float64}:
  68881.5
 104488.0
 115250.0
 135036.75
 171561.50000000044

In [27]:
quantile(voltas_HAM, [0.05, 0.9, 0.95, 0.975, 0.99])

5-element Vector{Float64}:
  69415.2
 104949.40000000001
 116783.79999999997
 142771.69999999998
 176811.55999999974

In [25]:
using Statistics
#quantile(dados[dados.driverId .== 3, :].milliseconds, [0.05, 0.9, 0.95, 0.975, 0.99])

In [ ]:
dados_ham = dados[dados.milliseconds .< 100000, :]
dados_ham = dados_ham[dados_ham.driverId .== 1, :]

In [ ]:
scatter(dados[dados.circuitId .== 1, :].lap, dados[dados.circuitId .== 1, :].milliseconds)

In [ ]:
quantile(dados.milliseconds, [0.05, 0.9, 0.95, 0.975, 0.99])

In [ ]:
hamilton = filter(row -> row.driverId == 1 , lap_times_raw);

In [ ]:
hamilton_race_1 = filter(row -> row.raceId == 841, hamilton);

In [21]:
using Plots 
gr()

Plots.GRBackend()

In [ ]:
histogram(hamilton_race_1.milliseconds, bins = 100);

In [ ]:
hamilton_race_2 = filter(row -> row.raceId == 1015, hamilton);

In [ ]:
#scatter(lap_times_raw.milliseconds, lap_times_raw.lap)

In [ ]:
race1015 = filter(row -> row.raceId == 1015 , lap_times_raw);

In [ ]:
using Statistics

In [ ]:
function mean_groups(grouped_data)    
    mean_times = Dict()
    for (j, i) in enumerate(keys(grouped_data))
        mean_ = mean(get(gd, i, nothing).milliseconds)
        driver = get(gd, i, nothing).driverId[1]
        mean_times[driver] = mean_  
    end
    return mean_times
end

In [ ]:
means = mean_groups(gd)

In [ ]:
delete!(means, 844)

In [ ]:
histogram(means, bin = 9)

In [ ]:
drivers_raw = DataFrame(CSV.File("C:/Users/liber/Documents/GitHub/Portifolio/F1_dataset/drivers.csv"));

In [ ]:
function drivers_dict(data)
    drivers = Dict()
    for i in 1:nrow(drivers_raw)
        ID = drivers_raw.driverId[i]
        driver = drivers_raw.surname[i]
        drivers[ID] = driver
    end
    return drivers
end

In [ ]:
nrow(drivers_raw)

In [ ]:
drivers = drivers_dict(drivers_raw)

In [ ]:
drivers[1]

In [ ]:
names(lap_times_raw)

In [ ]:
races = DataFrame(CSV.File("C:/Users/liber/Documents/GitHub/Portifolio/F1_dataset/races.csv"));

In [ ]:
first(races, 6)

In [ ]:
function races_dict(data)
    races_dictionary = Dict()
    for i in 1:nrow(data)
        ID = data.raceId[i]
        year = data.year[i]
        circuit = data.name[i]
        races_dictionary[ID] = (year, circuit)
    end
    return races_dictionary
end

In [ ]:
race_dict = races_dict(races)

In [ ]:
D = Dict('a'=>5, 'b'=>6)

In [ ]:
depois_de_2013 = [i for (i, j) in race_dict if j[1]>2013]
# filter(x -> x[1]> 2013, race_dict)