In [28]:
function triang_matrix(n)
    A = rand(Float32, n, n)
    for i in 1:(n-1)
        A[i, (i+1):n] .= 0
    end
    return A
end

triang_matrix (generic function with 1 method)

In [29]:
triang_matrix(5)

5×5 Matrix{Float32}:
 0.394314   0.0       0.0       0.0       0.0
 0.0493674  0.692755  0.0       0.0       0.0
 0.583679   0.45522   0.788291  0.0       0.0
 0.12443    0.379857  0.301348  0.308491  0.0
 0.695626   0.10194   0.239127  0.299864  0.100332

In [14]:
function sys_linear(A, B)
    X = zeros(length(B))
    X[1] = B[1]/A[1,1]
    for i in 2:length(B)
        soma = 0
        el = A[i, 1:(i-1)] .* X[1:(i-1)]
        soma += sum(el)
        X[i] = (B[i] - soma)/A[i,i]
    end
    return X
end


sys_linear (generic function with 1 method)

In [39]:
using BenchmarkTools

In [40]:
function teste(n)
    A = triang_matrix(n)
    B = rand(n)
    return sys_linear(A, B)
end

teste (generic function with 1 method)

In [41]:
teste1 = @benchmark teste(8)

BenchmarkTools.Trial: 10000 samples with 30 evaluations.
 Range (min … max):  913.333 ns … 179.610 μs  ┊ GC (min … max):  0.00% … 99.13%
 Time  (median):       1.057 μs               ┊ GC (median):     0.00%
 Time  (mean ± σ):     1.649 μs ±   4.600 μs  ┊ GC (mean ± σ):  10.30% ±  3.81%

  ██▆▅▄▃▁▁▁▂▂▂▂▃▂▁▁   ▆▅▃▂▂▁▁   ▂▂                              ▂
  █████████████████████████████████▇▇▇▇▇▇▇▆▆▇▆▅▆▆▆▆▆▆▇▅▆▆▆▆▄▅▅▅ █
  913 ns        Histogram: log(frequency) by time       4.33 μs <

 Memory estimate: 2.36 KiB, allocs estimate: 24.

In [59]:
teste2 = @benchmark teste(16) 

BenchmarkTools.Trial: 10000 samples with 9 evaluations.
 Range (min … max):  1.944 μs … 385.933 μs  ┊ GC (min … max):  0.00% … 98.92%
 Time  (median):     2.211 μs               ┊ GC (median):     0.00%
 Time  (mean ± σ):   3.344 μs ±  10.130 μs  ┊ GC (mean ± σ):  10.52% ±  3.55%

  ▆█▅▄▄▄▃▂▂▁▁▁ ▁▂▂▁▂▂▂▂▂▁▁                                    ▁
  █████████████████████████████▇█▇▇▇▇▇▇▆▇▆▆▆▆▅▆▆▅▆▅▅▆▆▅▅▄▅▅▄▅ █
  1.94 μs      Histogram: log(frequency) by time      10.1 μs <

 Memory estimate: 6.44 KiB, allocs estimate: 48.

In [68]:
teste3 = @benchmark teste(16) 

BenchmarkTools.Trial: 10000 samples with 9 evaluations.
 Range (min … max):  1.856 μs … 407.511 μs  ┊ GC (min … max):  0.00% … 99.13%
 Time  (median):     2.133 μs               ┊ GC (median):     0.00%
 Time  (mean ± σ):   3.148 μs ±  10.130 μs  ┊ GC (mean ± σ):  11.21% ±  3.56%

  ▆█▆▄▄▅▃▃▂▁  ▁▁ ▁▂▂▁▂▂▂▁▁                                    ▁
  ████████████████████████████▇▇▇▇▇▇▇▇▇▇▇▇▆▆▇▅▅▅▅▆▄▅▅▅▅▆▅▅▅▄▅ █
  1.86 μs      Histogram: log(frequency) by time      9.43 μs <

 Memory estimate: 6.44 KiB, allocs estimate: 48.

In [22]:
mean(teste2).time/mean(teste1).time

1.6269140474125645

In [23]:
median(teste2).time/median(teste1).time

1.2110726643598615

In [28]:
m1 = mean(teste1)

BenchmarkTools.TrialEstimate: 
  time:             3.920 μs
  gctime:           199.607 ns (5.09%)
  memory:           2.69 KiB
  allocs:           24

In [29]:
m2 = mean(teste2)

BenchmarkTools.TrialEstimate: 
  time:             6.378 μs
  gctime:           803.718 ns (12.60%)
  memory:           7.94 KiB
  allocs:           48

In [30]:
ratio(m2, m1)

BenchmarkTools.TrialRatio: 
  time:             1.6269140474125645
  gctime:           4.0265009632817375
  memory:           2.953488372093023
  allocs:           2.0

In [31]:
judge(m2, m1)

BenchmarkTools.TrialJudgement: 
  time:   +62.69% => regression (5.00% tolerance)
  memory: +195.35% => regression (1.00% tolerance)


In [1]:
function eliminacao_gauss(A, B)
    Aumentada = hcat(A, B)
    for i in 1:(length(Aumentada[:,1]) -1)
        pivot_line = Aumentada[i, :]
        for j in (i+1):(length(Aumentada[:,1]))
            m = Aumentada[j, i]/pivot_line[i]
            #println(Aumentada[j, :])
            #println(pivot_line * m)
            Aumentada[j, :] -= (pivot_line * m) 
        end
    end
    return Aumentada #map(x-> x < 10^(-14) ? 0 : x, Aumentada)
end

eliminacao_gauss (generic function with 1 method)

In [2]:
function swap!(A, i, j)
    k = A[i, :]
    A[i, :] = A[j, :]
    A[j, :] = k
    return A
end

swap! (generic function with 1 method)

In [3]:
A = [1. -3. 3.
2. 3. -1.
4. -3. -1.]

3×3 Matrix{Float64}:
 1.0  -3.0   3.0
 2.0   3.0  -1.0
 4.0  -3.0  -1.0

In [5]:
B = [-4. 15. 19.]
B = transpose(B)

3×1 transpose(::Matrix{Float64}) with eltype Float64:
 -4.0
 15.0
 19.0

In [6]:
K = eliminacao_gauss(A, B)

3×4 Matrix{Float64}:
 1.0  -3.0   3.0  -4.0
 0.0   9.0  -7.0  23.0
 0.0   0.0  -6.0  12.0

In [8]:
A = transpose(K[:,1:3])

3×3 transpose(::Matrix{Float64}) with eltype Float64:
  1.0   0.0   0.0
 -3.0   9.0   0.0
  3.0  -7.0  -6.0

In [9]:
B = reverse(K[:,4])

3-element Vector{Float64}:
 12.0
 23.0
 -4.0

In [20]:
sys_linear(A, )

3-element Vector{Float64}:
 -4.0
  2.5555555555555554
 -2.0

In [27]:
A = [i*2 for i in 1:200 if i % 2==1]


100-element Vector{Int64}:
   2
   6
  10
  14
  18
  22
  26
  30
  34
  38
   ⋮
 366
 370
 374
 378
 382
 386
 390
 394
 398

In [9]:
map(x-> x > 0.5 ? x : 0, R)

5×5 Matrix{Real}:
 0.604473  0        0         0.852598  0.818641
 0.658509  0        0         0.751832  0.814486
 0         0        0.720789  0         0
 0         0.83157  0         0         0
 0         0        0         0.720592  0.759257

In [97]:
hcat(R, X)

5×6 Matrix{Float64}:
 0.420955   0.264446  0.480921  0.0617336  0.956795  0.5801
 0.0351192  0.843676  0.310527  0.716927   0.80256   0.900945
 0.787293   0.344067  0.92614   0.801492   0.93447   0.0899753
 0.531836   0.913958  0.735869  0.0649295  0.223294  0.728658
 0.152925   0.370884  0.202385  0.580076   0.421497  0.597866

In [103]:
escalonada = eliminacao_gauss(R, X)

5×6 Matrix{Real}:
 0.52871  0.602807  0.92134   0.350632  0.347927  0.97873
 0        0         0         0.638917  0.28932   0
 0        0         0.508209  0.161531  0.259953  0.127413
 0        0         0         0.196478  0.990114  0
 0        0         0         0         0         0.366225

In [110]:
sys_linear(escalonada[:,1:5], escalonada[:,6])

5-element Vector{Float64}:
   1.85116777965951
 NaN
 NaN
 NaN
 NaN

In [45]:
0.658509/0.604473

1.0893935709287264

In [46]:
0.397493/0.604473

0.6575860294835335