In [1]:
using Distributions
using Statistics

In [2]:
k = 1_000_000
A = zeros(k,2)

1000000×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 ⋮    
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [16]:
A[:,1] = rand(Binomial(2, 1/3), k)

1000000-element Vector{Int64}:
 1
 0
 1
 0
 1
 1
 1
 2
 1
 0
 ⋮
 0
 0
 1
 1
 1
 2
 0
 1
 0

In [18]:
A[:,2] = rand(Binomial(2, 1/3), k) + A[:,1]

1000000-element Vector{Float64}:
 2.0
 1.0
 1.0
 0.0
 1.0
 3.0
 3.0
 3.0
 3.0
 0.0
 ⋮
 0.0
 0.0
 1.0
 1.0
 1.0
 3.0
 0.0
 2.0
 0.0

In [19]:
A

1000000×2 Matrix{Float64}:
 1.0  2.0
 0.0  1.0
 1.0  1.0
 0.0  0.0
 1.0  1.0
 1.0  3.0
 1.0  3.0
 2.0  3.0
 1.0  3.0
 0.0  0.0
 ⋮    
 0.0  0.0
 0.0  0.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 2.0  3.0
 0.0  0.0
 1.0  2.0
 0.0  0.0

In [21]:
var(A[:,1] - A[:,2], corrected = false)

0.44512633598399964

In [57]:
var(A[:,2], corrected = false) + var(A[:,1], corrected = false)

1.3325458202140008

In [26]:
var(A[:,2], corrected = false) + var(A[:,1], corrected = false) - 2*cov(A[:,2], A[:,1], corrected = false)

0.44512633598404483

In [33]:
N4 = pdf(Binomial(4, 1/3)) .* [0, 1, 2, 3, 4]

5-element Vector{Float64}:
 0.0
 0.39506172839506165
 0.5925925925925923
 0.2962962962962963
 0.0493827160493827

In [52]:
sum(N4)

1.333333333333333

In [34]:
N2 = pdf(Binomial(2, 1/3)) .* [0, 1, 2]

3-element Vector{Float64}:
 0.0
 0.44444444444444436
 0.22222222222222207

In [38]:
Final = N4 * transpose(N2)

5×3 Matrix{Float64}:
 0.0  0.0        0.0
 0.0  0.175583   0.0877915
 0.0  0.263374   0.131687
 0.0  0.131687   0.0658436
 0.0  0.0219479  0.0109739

In [40]:
xy = sum(Final)

0.8888888888888883

In [48]:
(2/9 * 2) - (2 * (xy - 8/9))

0.44444444444444553

In [49]:
n = 4
p = 1/3

0.3333333333333333

In [50]:
n*p*(1-p) + n^2*p^2

2.6666666666666665

In [51]:
E2 = pdf(Binomial(4, 1/3)) .* [0, 1, 4, 9, 16]

5-element Vector{Float64}:
 0.0
 0.39506172839506165
 1.1851851851851847
 0.8888888888888888
 0.1975308641975308

In [53]:
sum(E2)

2.666666666666666

In [54]:
sum(E2) - (sum(N4))^2

0.8888888888888891

In [56]:
2*p*(1-p)

0.4444444444444445

In [25]:
transition = [
1 0 0 0 0
0.6 0 0.4 0 0
0 0.6 0 0.4 0
0 0 0.6 0 0.4
0 0 0 0 1]

5×5 Matrix{Float64}:
 1.0  0.0  0.0  0.0  0.0
 0.6  0.0  0.4  0.0  0.0
 0.0  0.6  0.0  0.4  0.0
 0.0  0.0  0.6  0.0  0.4
 0.0  0.0  0.0  0.0  1.0

In [28]:
stationary = transition ^ 100_000_000

5×5 Matrix{Float64}:
 1.0       0.0  0.0  0.0  0.0
 0.876923  0.0  0.0  0.0  0.123077
 0.692308  0.0  0.0  0.0  0.307692
 0.415385  0.0  0.0  0.0  0.584615
 0.0       0.0  0.0  0.0  1.0

In [29]:
transpose([1/5, 1/5, 1/5, 1/5, 1/5]) * stationary 

1×5 transpose(::Vector{Float64}) with eltype Float64:
 0.596923  0.0  0.0  0.0  0.403077

In [30]:
a = [0; 1/3; 1/3; 1/3; 0]

5-element Vector{Float64}:
 0.0
 0.3333333333333333
 0.3333333333333333
 0.3333333333333333
 0.0

In [31]:
transpose(a) * stationary 

1×5 transpose(::Vector{Float64}) with eltype Float64:
 0.661538  0.0  0.0  0.0  0.338462