In [1]:
import pandas as pd 
import numpy as np 

In [2]:
train_data = pd.read_csv(r"C:\Users\liber\Documents\Datasets\Titanic\train.csv")

In [3]:
train_data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [4]:
train_data.drop(["PassengerId", "Name", "Ticket", "Cabin"], axis=1 ,inplace=True)

In [5]:
test_data = pd.read_csv(r"C:\Users\liber\Documents\Datasets\Titanic\test.csv")
test_data

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0              330911    7.8292   NaN        Q  
1    female  47.0      1      0              363272    7.0000   NaN        S  
2      male  62.0      0      0              240276    9.6875   NaN        Q  
3      male  27.0      0      0              315154    8.6625   NaN        S  
4    female  22.0      1      1             3101298   12.2875   NaN        S  
..      ...   ...    ...    ...                 ...       ...   ...      ...  
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  female  39.0      0      0            PC 17758  108.9000  C105        C  
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416    male   NaN      0      0              359309    8.0500   NaN        S  
417    male   NaN      1      1                2668   22.3583   NaN        C  

[418 rows x 11 columns]

In [6]:
train_data.isna().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [7]:
train_data[train_data["Sex"] == "female"].Age.mean()

27.915708812260537

In [8]:
train_data[train_data["Sex"] == "male"].Age.mean()

30.72664459161148

In [9]:
train_data[train_data["Pclass"] == 1].Age.mean()

38.233440860215055

In [10]:
train_data[train_data["Pclass"] == 2].Age.mean()

29.87763005780347

In [11]:
train_data[train_data["Pclass"] == 3].Age.mean()

25.14061971830986

In [12]:
from sklearn.preprocessing import OneHotEncoder

In [13]:
encoder = OneHotEncoder(handle_unknown='ignore', drop='first', sparse_output=False)
encoder.fit(train_data[["Sex", "Pclass", "Embarked"]])

OneHotEncoder(drop='first', handle_unknown='ignore', sparse_output=False)

In [14]:
train_transformed = encoder.transform(train_data[["Sex", "Pclass", "Embarked"]])

In [15]:
train_transformed = np.hstack((train_data.drop(["Sex", "Pclass", "Embarked"], axis=1), train_transformed))

In [16]:
Y_train = train_transformed[:,0]
X_train = train_transformed[:,1:]

In [17]:
from sklearn.impute import KNNImputer

In [18]:
imputer = KNNImputer(n_neighbors=10)
X_train = imputer.fit_transform(X_train)

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train

array([[22. ,  1. ,  0. , ...,  0. ,  1. ,  0. ],
       [38. ,  1. ,  0. , ...,  0. ,  0. ,  0. ],
       [26. ,  0. ,  0. , ...,  0. ,  1. ,  0. ],
       ...,
       [25.3,  1. ,  2. , ...,  0. ,  1. ,  0. ],
       [26. ,  0. ,  0. , ...,  0. ,  0. ,  0. ],
       [32. ,  0. ,  0. , ...,  1. ,  0. ,  0. ]])

In [21]:
X_train_final, X_val, y_train_final, y_val = train_test_split(X_train, Y_train, test_size=0.20, random_state=42)

In [22]:
from sklearn.linear_model import LogisticRegression

In [23]:
log_reg = LogisticRegression(random_state=10, solver='lbfgs', max_iter=1000).fit(X_train_final, y_train_final)
log_reg.score(X_train_final, y_train_final)

0.8103932584269663

In [24]:
log_reg.score(X_val, y_val)

0.8044692737430168

In [25]:
from sklearn.ensemble import AdaBoostClassifier

In [26]:
adab = AdaBoostClassifier(n_estimators=350, random_state=10).fit(X_train_final, y_train_final)
adab.score(X_train_final, y_train_final)

0.8651685393258427

In [27]:
adab.score(X_val, y_val)

0.8212290502793296

In [28]:
from sklearn.ensemble import GradientBoostingClassifier

In [29]:
gbc = GradientBoostingClassifier(n_estimators=162, random_state=10).fit(X_train_final, y_train_final)
gbc.score(X_train_final, y_train_final)

0.9213483146067416

In [30]:
gbc.score(X_val, y_val)

0.8212290502793296

In [31]:
gbc = GradientBoostingClassifier(n_estimators=185, random_state=10).fit(X_train_final, y_train_final)
gbc.score(X_val, y_val)

0.8324022346368715

In [32]:
gbc = GradientBoostingClassifier(n_estimators=170, random_state=10).fit(X_train_final, y_train_final)
gbc.score(X_val, y_val)

0.8324022346368715

In [33]:
test_data.drop(["PassengerId", "Name", "Ticket", "Cabin"], axis=1 ,inplace=True)

In [34]:
X_test = np.hstack((test_data.drop(["Sex", "Pclass", "Embarked"], axis=1), encoder.transform(test_data[["Sex", "Pclass", "Embarked"]])))

In [35]:
X_test

array([[34.5,  0. ,  0. , ...,  1. ,  0. ,  0. ],
       [47. ,  1. ,  0. , ...,  0. ,  1. ,  0. ],
       [62. ,  0. ,  0. , ...,  1. ,  0. ,  0. ],
       ...,
       [38.5,  0. ,  0. , ...,  0. ,  1. ,  0. ],
       [ nan,  0. ,  0. , ...,  0. ,  1. ,  0. ],
       [ nan,  1. ,  1. , ...,  0. ,  0. ,  0. ]])

In [36]:
X_test = imputer.transform(X_test)

In [37]:
X_test

array([[34.5 ,  0.  ,  0.  , ...,  1.  ,  0.  ,  0.  ],
       [47.  ,  1.  ,  0.  , ...,  0.  ,  1.  ,  0.  ],
       [62.  ,  0.  ,  0.  , ...,  1.  ,  0.  ,  0.  ],
       ...,
       [38.5 ,  0.  ,  0.  , ...,  0.  ,  1.  ,  0.  ],
       [28.15,  0.  ,  0.  , ...,  0.  ,  1.  ,  0.  ],
       [22.7 ,  1.  ,  1.  , ...,  0.  ,  0.  ,  0.  ]])

In [39]:
gbc_final = GradientBoostingClassifier(n_estimators=170, random_state=10).fit(X_train, Y_train)

In [40]:
gbc_final.score(X_train, Y_train)

0.9124579124579124

In [41]:
RESULTADOS = gbc_final.predict(X_test)

In [42]:
RESULTADOS

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0.,
       0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0.,
       0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0.,
       0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1.,
       1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 1.

In [48]:
RESULTADOS = RESULTADOS.astype(int)

In [49]:
RESULTADOS

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [50]:
test_data = pd.read_csv(r"C:\Users\liber\Documents\Datasets\Titanic\test.csv")

In [51]:
test_data.insert(loc=1, column='Survived', value=RESULTADOS)

In [52]:
test_data

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         0       3   
2            894         0       2   
3            895         0       3   
4            896         0       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                                            ...     ...   ...    ...    ...   
413                            Spector, Mr. Woolf    male   NaN      0      0   
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0   
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0   
416                           Ware, Mr. Frederick    male   NaN      0      0   
417                      Peter, Master. Michael J    male   NaN      1      1   

                 Ticket      Fare Cabin Embarked  
0                330911    7.8292   NaN        Q  
1                363272    7.0000   NaN        S  
2                240276    9.6875   NaN        Q  
3                315154    8.6625   NaN        S  
4               3101298   12.2875   NaN        S  
..                  ...       ...   ...      ...  
413           A.5. 3236    8.0500   NaN        S  
414            PC 17758  108.9000  C105        C  
415  SOTON/O.Q. 3101262    7.2500   NaN        S  
416              359309    8.0500   NaN        S  
417                2668   22.3583   NaN        C  

[418 rows x 12 columns]

In [53]:
test_data[["PassengerId", "Survived"]].to_csv(r"C:\Users\liber\Documents\GitHub\Portifolio\Kaggle\Titanic_respostas2.csv", index=False)

In [68]:
log_reg = LogisticRegression(penalty='l2', random_state=10, solver='liblinear', max_iter=100000).fit(X_train_final, y_train_final)
log_reg.score(X_train_final, y_train_final)

0.8103932584269663

In [69]:
log_reg_final = LogisticRegression(penalty='l2', random_state=10, solver='liblinear', max_iter=100000).fit(X_train, Y_train)
log_reg_final.score(X_train, Y_train)

0.8103254769921436

In [70]:
RESULTADOS_2 = log_reg_final.predict(X_test)
RESULTADOS_2

array([0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0.,
       0., 1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0.,
       0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1.,
       1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1.,
       0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 1.

In [71]:
RESULTADOS_2 = RESULTADOS_2.astype(int)
test_data = pd.read_csv(r"C:\Users\liber\Documents\Datasets\Titanic\test.csv")
test_data.insert(loc=1, column='Survived', value=RESULTADOS_2)

In [72]:
test_data

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         0       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                                            ...     ...   ...    ...    ...   
413                            Spector, Mr. Woolf    male   NaN      0      0   
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0   
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0   
416                           Ware, Mr. Frederick    male   NaN      0      0   
417                      Peter, Master. Michael J    male   NaN      1      1   

                 Ticket      Fare Cabin Embarked  
0                330911    7.8292   NaN        Q  
1                363272    7.0000   NaN        S  
2                240276    9.6875   NaN        Q  
3                315154    8.6625   NaN        S  
4               3101298   12.2875   NaN        S  
..                  ...       ...   ...      ...  
413           A.5. 3236    8.0500   NaN        S  
414            PC 17758  108.9000  C105        C  
415  SOTON/O.Q. 3101262    7.2500   NaN        S  
416              359309    8.0500   NaN        S  
417                2668   22.3583   NaN        C  

[418 rows x 12 columns]

In [ ]:
test_data[["PassengerId", "Survived"]].to_csv(r"C:\Users\liber\Documents\GitHub\Portifolio\Kaggle\Titanic_respostas3.csv", index=False)